### ISSUE TITLE
Which fields are requested by a query ?

### ISSUE THREAD

**Issue by flintforge** [status-im/nim-graphql#102]
First of all, thanks a lot for that project.  I'm surprised it doesn't get more love, because it looks very promising.

I'm trying to figure which fields are requested by a query, as explained here: https://gqlgen.com/reference/field-collection/
As the parent node is an empty map in the query — e.g. `proc queryX(ud: RootRef, params: Args, parent: Node)` —
I made it using an _instrument_ with the following function.
However I don't find t find a proper way to provide to the query the result an instrument returned.
Any example or idea ?

``` nim
#+begin_src nim
type
  QueryFieldSet* = ref object of InstrumentRef

proc queryFields(ud: InstrumentRef, flag: InstrumentFlag,
                 params, node: Node): InstrumentResult
                 {.cdecl, gcsafe, raises: [Defect, CatchableError].} =
  let
    qc = QueryFieldSet(ud)
    exec = ExecRef(node.sym.exec)
  var  
    fields:seq[string]

  for f in exec.fieldSet:
    for s in f.field.sels.sons:
      for n in s.sons:
        if n.kind == nkName:
          proj.add(n.name.s)

  try: debug($fields) 
  except:  error getCurrentExceptionMsg()
  ok()
  
proc new*(_: type QueryFieldSet): QueryFieldSet =
  var qc = QueryFieldSet()
  qc.iProc = queryFields
  qc.flags = {iExecBegin}
  qc 
#+end_src
```

**Comment by jangko** [comment]
```Nim
type
  MyContext = ref object of GraphqlRef
     whateverField: whateverType    # store your instrument result here

  QueryFieldSet* = ref object of InstrumentRef
     ctx: MyContext 

... # the rest of your code

proc new*(_: type QueryFieldSet, ctx: MyContext): QueryFieldSet =
   QueryFieldSet(
      iProc: queryFields,
      flags: {iExecBegin},
      ctx: ctx
   )
```

The `GraphqlRef` reference always passed to each resolver, and currently you can setup your code like above.
I know it creates cyclic reference, but I think it's ok because both the Graphql and Intrument object are expected to have long lifetime.

**Comment by flintforge** [comment]
Yes, that's it !
I just had to initialize the `NameCache` and now the context can travel in the resolvers.
```nim
  var ud = QueryContext()
  ud.names = newNameCache()
  var qc = QueryFieldSet.new(ud)
```
Extra question: what does `ud` stands for in `ud: RootRef` ?`

**Comment by jangko** [comment]
ud = `User Data`
