### ISSUE TITLE
Incorrect Accept-Encoding value error

### ISSUE THREAD

**Issue by EriKWDev** [status-im/nim-graphql#94]
It seems that my browser by default adds the header `Accept-Encoding:  gzip, deflate, br`, which causes the graphql server to respond with :
```json
{
    "errors": [
        {
            "message": "Incorrect Accept-Encoding value"
        }
    ]
}
```

When using postman I can remove the Accept-Encoding header from the post request and then it seems to work fine. Is this normal? This happens both for the playground examples and for my initial test server using the package.

**Comment by EriKWDev** [comment]
![image](https://user-images.githubusercontent.com/19771356/124100490-cf9ebd80-da5e-11eb-89f6-6ef312b3db2f.png)

**Comment by jangko** [comment]
This is a bug Graphql HTTP server.
